### ISSUE TITLE
Allow using git_testament! in a context that expects a literal

### ISSUE THREAD

**Issue by jyn514** [kinnison/git-testament#10]
Use case: I want the help message for my CLI tool to be a `const &'static str`.
Problem: `git_testament!` generates a struct that implements `Display` instead of a `&str` (and furthermore, going through any trait such as `Display` can't be done in a const context)

It would be great to make it possible to use git_testament in a `const` context.

Possible workaround on my end: generate the struct in `build.rs` and send the Display of that struct as an environment variable through to `main.rs`.

**Comment by kinnison** [comment]
(Apologies ahead of time, this is a bit of a ramble as I explore the problem)

This is an interesting use-case.  One of the original purposes of `git_testament!` was to ensure that `build.rs` related problems of not noticing code changes and thus not updating the testament was avoided, so I'd surely like to provide a solution for you which doesn't result in your resorting to `build.rs`.

Firstly, a long-shot -- could you put your testament render into something like the (untested) following?

```rust
lazy_static! {
    static ref TESTAMENT: String = {
        git_testament!(INNER_TESTAMENT);
        render_testament!(INNER_TESTAMENT)
    };
}
```

Assuming not, then we need to define some suitable mechanism for allowing you to select the subset of information in the testament structure so that a true static string can be generated by the proc macro.  Given that by default, the rendered testament includes `CARGO_PKG_VERSION` in some circumstances, the output of the proc macro is likely to have to be a call to `concat!()` and friends, will that be okay for you?

What I imagine is, in the simple case, something like:

```rust
const TESTAMENT: &'static str = static_testament!();
```

When the caller wishes to indicate the trusted branch:

```rust
const TESTAMENT: &'static str = static_testament!("stable");
```

One thing I'm worried about is making it so that testament rendering is duplicated in both the proc macro and the crate used by apps which actually want access to all the data.  In theory I could do this by making a third underlying types crate to shuffle things around, but I'd like to try and find something better.  Suggestions welcome.

**Comment by jyn514** [comment]
>  One of the original purposes of git_testament! was to ensure that build.rs related problems of not noticing code changes

Oof, I hadn't even thought of that. Yeah I would definitely like to avoid `build.rs` then.

> Firstly, a long-shot -- could you put your testament render into something like the (untested) following?

Unfortunately not, since I then pass it to `concat!`: 
```
error: expected a literal
  --> src/main.rs:41:34
   |
41 |     env!("CARGO_PKG_NAME"), " ", TESTAMENT, "\n",
   |                                  ^^^^^^^^^
   |
   = note: only literals (like `"foo"`, `42` and `3.14`) can be passed to `concat!()`
```
Using `render_testament!` directly (`env!("CARGO_PKG_NAME"), " ", render_testament!(TESTAMENT), "\n",`) gives the same error.

> the output of the proc macro is likely to have to be a call to concat!() and friends, will that be okay for you?

Sure, that's fine.

> One thing I'm worried about is making it so that testament rendering is duplicated in both the proc macro and the crate used by apps which actually want access to all the data.

The way [`target_lexicon` handles this]( https://github.com/bytecodealliance/target-lexicon/blob/master/build.rs#L14) for `build.rs` is by having a file that's included both in the `build.rs` and the main build. Maybe you could do something similar with code that's included both in the proc-macro and the crate?

**Comment by kinnison** [comment]
cf. code included in both proc-macro and the main crate, Hrm, I suppose I could do that via `file` attributes on a mod.

**Comment by kinnison** [comment]
I decided in the end that for now I'll duplicate the logic and have tests to ensure they come out the same at least for the test cases -- as such a first-cut of this is now in master.  If you could take a look at https://github.com/kinnison/git-testament/blob/master/git-testament-derive/src/lib.rs#L436 and if that looks sane let me know and I'll grind the release machinery then that'd be excellent.

**Comment by jyn514** [comment]
> you can optionally specify a branch name which will be considered the "trusted" branch like in `git_testament::render_testament!()`

What does "trusted" mean in this context?

It looks like the same comment is repeated above `git_testament_macros!(version);` both times in the examples, is that intentional? I had to read it twice to make sure I wasn't getting lost in the code.

**Comment by jyn514** [comment]
Other than that though, this looks great!

```
$ cargo run -q -- --help | head -n 1
rcc 0.8.0+309 (c8934eb3a 2020-05-09) dirty 29 modifications
```

**Comment by kinnison** [comment]
I think trusted branches aren't explained well, I'll fix the docs on those and then make a release!

**Comment by kinnison** [comment]
Version 0.1.9 released.
