### ISSUE TITLE
clippy warns with `clippy::needless_update` when using the `git_testament!` macro

### ISSUE THREAD

**Issue by magicmaaaaan** [kinnison/git-testament#6]
Hi, I saw this library in the latest release of rustup, and it's much nicer than the typical `build.rs` method!

I noticed when adding it to my program, clippy gives the `clippy::needless_update` warning when using the `git_testament!` macro. This is with git-testament 0.1.4 and git-testament-derive 0.1.5.

```
$ rustc --version
rustc 1.34.1 (fc50f328b 2019-04-24)
$ cargo --version
cargo 1.34.0 (6789d8a0a 2019-04-01)
$ cargo clippy --version
clippy 0.0.212 (726176e3 2019-04-18)
$ cargo clippy
   Compiling foo v0.1.0 (/home/magicmaaaaan/foo)
warning: struct update has no effect, all the fields in the struct have already been specified
  --> src/main.rs:11:1
   |
11 | git_testament!(TESTAMENT);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(clippy::needless_update)] on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_update

    Finished dev [unoptimized + debuginfo] target(s) in 2.76s
```

**Comment by kinnison** [comment]
Hi,

Thanks for taking the time to look at `git_testament` and to file this issue.  The struct initialiser is used in an attempt to be more forward-compatible and to reduce the exact-tie between `git_testament` and `git_testament_derive` -- As such, I think the right answer is to silence that clippy lint rather than to remove it.  I shall sort out a patch so that the next release of `git_testament_derive` has `#[allow(clippy::needless_update)]` on the requisite item.  In the meantime, you can probably silence that by putting it on the `git_testament!(TESTAMENT);` statement if you want.

Thanks again,

D.
